apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: fre-ipa02
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "ipa02-server-network",
      "type": "ipvlan",
      "device": "br-ex",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.1.1.216/24"
          }
        ]  
      }
    }
