apiVersion: v1
kind: PersistentVolume
metadata:
  name: testpod-nfs-frest01
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    path: /nfs/testme
    server: 10.1.1.131
