apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"testpod:0.3"},"fieldPath":"spec.template.spec.containers[?(@.name==\"testpod\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2023-12-07T10:16:40Z"
  generation: 5
  labels:
    app: testpod
    app.kubernetes.io/component: testpod
    app.kubernetes.io/instance: testpod
  name: testpod
  namespace: fre-ipa-409
  resourceVersion: "218616057"
  uid: 7544ccf4-7ee3-4599-888b-a2de95e36181
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: testpod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: fre-ipa02
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: testpod
    spec:
      containers:
      - image: quay.io/jfreygner/testpod@sha256:3f507fe573223d584e441f6604a54da080232315a492f607a5d123c49fbe4849
        imagePullPolicy: IfNotPresent
        name: testpod
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: testpod-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: testpod-volume-1
status:
  conditions:
  - lastTransitionTime: "2023-12-07T10:16:57Z"
    lastUpdateTime: "2023-12-07T10:16:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-12-07T10:16:40Z"
    lastUpdateTime: "2023-12-07T10:52:32Z"
    message: ReplicaSet "testpod-58d474f4db" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
