apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpod-nfs-frest01-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: testpod-nfs-frest01
