apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpod-data-ovirt-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: ovirt-csi-sc
