apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpod-data-iscsi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: testpod-data-iscsi
