apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpod-data-ocs-storagecluster-cephfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: ocs-storagecluster-cephfs
