apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpod-data-ocs-block-ssd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: fre-ocs-block-office01-ssd02
